version: '3.8'

services:
  # 1. Microservicio USUARIOS
  usuarios:
    build: ./usuarios
    container_name: ms_usuarios
    ports:
      - "8180:8180"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://34.176.27.161:3306/usuario
      - SPRING_DATASOURCE_USERNAME=huerto-admin
      - SPRING_DATASOURCE_PASSWORD=Zu0=lKu/`XU:DAtY
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  # 2. Microservicio CARRITO
  carrito:
    build: ./carrito
    container_name: ms_carrito
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://34.176.27.161:3306/usuario
      - SPRING_DATASOURCE_USERNAME=huerto-admin
      - SPRING_DATASOURCE_PASSWORD=Zu0=lKu/`XU:DAtY
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  # 3. Microservicio CORE (si existe)
  core:
    build: ./core
    container_name: ms_core
    ports:
      - "8182:8182"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://34.176.27.161:3306/usuario
      - SPRING_DATASOURCE_USERNAME=huerto-admin
      - SPRING_DATASOURCE_PASSWORD=Zu0=lKu/`XU:DAtY
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped